spring:
  application:
    name: musalog-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/credit-card-db
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
  cloud:
    consul:
      host: ${CONSUL_HOST:127.0.0.1}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}::${spring.application.instance_id:${random.value}}
        prefer-ip-address: true
        register: true
        enabled: true
        deregister: on
      enabled: true

server:
  port: 8082

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 120
  expiration-refresh: 2400
  issuer: terenin

yoo:
  secret: test_qGBrshosm2pneVOrW_IFSt2NI4whC_JvQMwaP_-3HWU
  id: 223654
  price: 200

